/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Tenis;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SOLECITO
 */
public class TenisMarcador extends javax.swing.JFrame {
    

    /**
     * Creates new form marcador
     */
    public TenisMarcador() {
        initComponents();
        
        }
        private int ScoreP1 = 0;
	private int ScoreP2 = 0;
        private Idiomas idioma;
        public String jugador1;
        public String jugador2;
        
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jugador1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jugador2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("CERO-IGUALES");

        jButton3.setText("español");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("ingles");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("frances");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("RESET");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Aleman");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jugador1", "Jugador2", "Puntuacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setAutoscrolls(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(200);

        jLabel2.setText("Nombre Jugador 1");

        jLabel3.setText("Nombre Jugador 2");

        jButton8.setText("Agregar Jugador");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("JUGADORES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(jButton2)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jButton8))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(27, 27, 27)
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton7))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton5)
                    .addComponent(jButton7)
                    .addComponent(jButton4))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton8)
                        .addGap(71, 71, 71))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        puntoP1();
        jLabel1.setText(score());
        ///Tabla
        imprimirTabla();                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        puntoP2();
        jLabel1.setText(score());
        ///Tabla
        imprimirTabla();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jButton4.setVisible(false);
        jButton5.setVisible(false);
        jButton7.setVisible(false);
        idioma= new IdiomaEspanol();
        
        imprimirTabla();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jButton3.setVisible(false);
        jButton5.setVisible(false);
        jButton7.setVisible(false);
        idioma=new IdiomaIngles();
        
        imprimirTabla();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jButton7.setVisible(false);
        idioma=new IdiomaFrances();
        
        imprimirTabla();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       ScoreP1 = 0;
       ScoreP2 = 0;
       ///jLabel1.setText("LOVE-ALL");
       
       jButton1.setEnabled(true);
       jButton2.setEnabled(true);
       jButton3.setVisible(true);
       jButton4.setVisible(true);
       jButton5.setVisible(true);
       jButton7.setVisible(true);
       
       jButton1.setText("jugador1");
       jButton2.setText("jugador2");
       jTextField1.setText(" ");
       jTextField2.setText(" ");
       borrarTabla(0);
       imprimirTabla();
       
               
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
        idioma=new IdiomaAleman();
        
        imprimirTabla();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        ScoreP1 = (int) jTable1.getValueAt(row, 0);
        ScoreP2 = (int) jTable1.getValueAt(row, 1);
        borrarTabla(row+1);
        jLabel1.setText(score());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jugador1=jTextField1.getText();
        jugador2=jTextField2.getText();
        jButton1.setText(jugador1);
        jButton2.setText(jugador2);
    }//GEN-LAST:event_jButton8ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TenisMarcador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TenisMarcador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TenisMarcador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TenisMarcador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TenisMarcador().setVisible(true);
            }
        });
    }
    
    private void puntoP1() {
        ScoreP1++;
    }

    private void puntoP2() {
        ScoreP2++;
    }
    
    public String score() {
                if (ganador()) {
			return getIdioma().getWin()+" "+MarcadorMasAlto();
		}

		if (TieneVentaja()) { 
			return getIdioma().getAdvantage() +" "+MarcadorMasAlto(); 
		}

		if (Empate())
			return getIdioma().getDeuce();

		if(ScoreP1 == ScoreP2) {
			return CambiaScore(ScoreP1) +" "+getIdioma().getAll();
		}
                return CambiaScore(ScoreP1) + " - " + CambiaScore(ScoreP2);
	}
    
       private boolean Empate() {
		return ScoreP1 >= 3 && ScoreP2 == ScoreP1;
	}

	private String MarcadorMasAlto() {
		if (ScoreP1 > ScoreP2) {
			return jTextField1.getText();//+getIdioma().getPlayer()+ " 1";
		} else {
			return jTextField2.getText();//+getIdioma().getPlayer()+ " 2";
		}
	}

	private boolean ganador() {
		if(ScoreP2 >= 4 && ScoreP2 >= ScoreP1 + 2 )
			return true;
		if(ScoreP1 >= 4 && ScoreP1 >= ScoreP2 + 2)
			return true;
		return false;
	}

	private boolean TieneVentaja() {
		if (ScoreP2 >= 4 && ScoreP2 == ScoreP1 + 1)
			return true;
		if (ScoreP1 >= 4 && ScoreP1 == ScoreP2 + 1)
                    return true;
		return false;
	}
       private String CambiaScore(int score) {
           switch (score) {
		case 3:
			return getIdioma().getForty();
		case 2:
			return getIdioma().getThirty();
		case 1: 
			return getIdioma().getFifteen();
		case 0:
			return getIdioma().getZero();
            }
		throw new IllegalArgumentException("Illegal score: " + score);
        }
       /////////////////////////////////////////////////////////////////
        void imprimirTabla(){
           DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            modelo.addRow(new Object[]{ScoreP1,ScoreP2,score()});
        }
        void borrarTabla(int row){
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            while (row < modelo.getRowCount()){
                modelo.removeRow(row);
            }
        }
        private void setIdioma(Idiomas idioma){
            this.idioma= idioma;
        }
        private Idiomas getIdioma(){
            return idioma;
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}

interface Idiomas {
    public String getZero();
    public String getFifteen();
    public String getThirty();
    public String getForty();
    public String getAll();
    public String getDeuce();
    public String getAdvantage();
    public String getWin();
    public String getPlayer();
}
////////////////////////////////////////////////////INGLES
class IdiomaIngles implements Idiomas{
    @Override
    public String getZero(){
        return "Love";
    }

    @Override
    public String getFifteen() {
        return "Fifteen";
    }

    @Override
    public String getThirty() {
        return "Thirty";
    }

    @Override
    public String getForty() {
        return "Forty";
    }

    @Override
    public String getAll() {
        return "All";
    }

    @Override
    public String getDeuce() {
        return "Deuce";
    }

    @Override
    public String getAdvantage() {
        return "Advantage for";
    }

    @Override
    public String getWin() {
        return "Wins";
    }
    
    @Override
    public String getPlayer() {
        return "Player";
    }
}
////////////////////////////////////////////////////ESPAÑOL
class IdiomaEspanol implements Idiomas{
    @Override
    public String getZero(){
        return "Cero";
    }

    @Override
    public String getFifteen() {
        return "Quince";
    }

    @Override
    public String getThirty() {
        return "Treinta";
    }

    @Override
    public String getForty() {
        return "Cuarenta";
    }

    @Override
    public String getAll() {
        return "Iguales";
    }

    @Override
    public String getDeuce() {
        return "Empate";
    }

    @Override
    public String getAdvantage() {
        return "Ventaja para";
    }

    @Override
    public String getWin() {
        return "Gana";
    }
    
    @Override
    public String getPlayer() {
        return "Jugador";
    }
}
////////////////////////////////////////////////////FRANCES
class IdiomaFrances implements Idiomas{
    @Override
    public String getZero(){
        return "Zero";
    }

    @Override
    public String getFifteen() {
        return "Quinze";
    }

    @Override
    public String getThirty() {
        return "Trente";
    }

    @Override
    public String getForty() {
        return "Quarente";
    }

    @Override
    public String getAll() {
        return "Á";
    }

    @Override
    public String getDeuce() {
        return "Égalité";
    }

    @Override
    public String getAdvantage() {
        return "Avantage pour";
    }

    @Override
    public String getWin() {
        return "Désir";
    }
    
    @Override
    public String getPlayer() {
        return "Joueur";
    }
}
////////////////////////////////////////////////////ALEMAN
class IdiomaAleman implements Idiomas{
    @Override
    public String getZero(){
        return "Liebe";
    }

    @Override
    public String getFifteen() {
        return "Vierzig";
    }

    @Override
    public String getThirty() {
        return "Dreibig";
    }

    @Override
    public String getForty() {
        return "Fünfzehn";
    }

    @Override
    public String getAll() {
        return "Alle";
    }

    @Override
    public String getDeuce() {
        return "Ziehen";
    }

    @Override
    public String getAdvantage() {
        return "Vorteil für";
    }

    @Override
    public String getWin() {
        return "Gewinnt";
    }
    
    @Override
    public String getPlayer() {
        return "Spieler";
    }
}